customhost = "database-testing.cgf3rbkwtlea.us-east-1.rds.amazonaws.com"
customuser = "admin1"
custompass = "12345678"
customdb = "database-testing"
custombucket = "testing-bucket-jor"
customregion = "us-east-1"
